version: '3.8'

services:

  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /app/
    volumes:
      - ./:/app/
    extra_hosts:
      - "host.docker.internal:host-gateway"
