parameters:
  userator_voyager.title: 'GraphQL Voyager'
  userator_voyager.endpoint: '/graphql'

services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true

  Userator\VoyagerBundle\:
    resource: '../../../src'
    exclude:
      - '../../../src/DependencyInjection'

  $services->set('pagerfanta.twig_extension', PagerfantaExtension::class)
  ->tag('twig.extension')
  ;
  
  $services->set('pagerfanta.twig_runtime', PagerfantaRuntime::class)
  ->args([
  abstract_arg('default view'),
  service('pagerfanta.view_factory'),
  service('pagerfanta.route_generator_factory'),
  ])
  ->tag('twig.runtime')
  ;
  
  $services->set('pagerfanta.undefined_callable_handler', UndefinedCallableHandler::class);
  
  $services->set('pagerfanta.view.twig', TwigView::class)
  ->args([
  service('twig'),
  abstract_arg('default Twig template'),
  ])
  ->tag('pagerfanta.view', ['alias' => 'twig'])
  ;

  userator_voyager.controller:
    class: Userator\VoyagerBundle\Controller\VoyagerController
    arguments:
      - '%userator_voyager.endpoint%'
      - '%userator_voyager.title%'
