parameters:
  userator_voyager.endpoint: '/graphql'

services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true

  Userator\VoyagerBundle\:
    resource: '../../../src'
    exclude:
      - '../../../src/DependencyInjection'

  userator_voyager.controller:
    class: Userator\VoyagerBundle\Controller\VoyagerController
    arguments:
      - '%userator_voyager.endpoint%'
