parameters:
  userator_voyager.enabled: true
  userator_voyager.title: 'GraphQL Voyager'
  userator_voyager.asset_package: 'voyager'

services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true

  Userator\VoyagerBundle\:
    resource: '../../../src'
    exclude:
      - '../../../src/DependencyInjection'

  userator_voyager.twig:
    alias: twig

  userator_voyager.router:
    alias: router

  userator_voyager.action:
    class: Userator\VoyagerBundle\Action\VoyagerAction
    arguments:
      - '@userator_voyage.twig'
      - '@userator_voyage.router'
      - '%userator_voyager.enabled%'
      - '%userator_voyager.title%'
      - '%userator_voyager.asset_package%'
